### ISSUE TITLE
Error500: Don't work for translations from ES (spanish) to EN (english)

### ISSUE THREAD

**Issue by rubdottocom** [imankulov/linguee-api#4] opened 2019-03-03 23:36 UTC
I tried many words and sentences and each of them return a Error 500

This is your example of bacalhau:

* https://linguee-api.herokuapp.com/api?q=bacalao&src=es&dst=en

Suprisingly it works from ES to PT @_@

**Comment by imankulov** [comment] 2021-04-25 13:13
Closing it down as too old 😅 

Besides, it seems to work. If the issue is still relevant, please consider re-opening it. Thanks!

**Closed by imankulov** 2021-04-25 13:13 UTC
